### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Bo0oM** [neuroo/grabber#1]
Excuse me, how to solve this problem?
Python 2.7.3
Kali linux 
>bo0om@home ~/s/Grabber> python '/home/bo0om/soft/Grabber/grabber.py' 
>Start scanning... http://google.com/
>runSpiderScan @  http://google.com/  |   # 1
>runSpiderScan @  http://google.com/  |   # 0
>runSpiderScan @  http://google.com///preferences?hl=ru  |   # 0
>runSpiderScan @  http://google.com///chrome/index.html?hl=ru&brand=CHNG&utm_source=ru-hpp&utm_medium=hpp&utm_campaign=ru  |   # 0
>runSpiderScan @  http://google.com///advanced_search?hl=ru&authuser=0  |   # 0
>runSpiderScan @  http://google.com///language_tools?hl=ru&authuser=0  |   # 0
>Traceback (most recent call last):
>  File "/home/bo0om/soft/Grabber/grabber.py", line 510, in <module>
>    spider(archives_url, depth)
>  File "/home/bo0om/soft/Grabber/spider.py", line 517, in spider
>    runSpiderScan(root, depth)
>  File "/home/bo0om/soft/Grabber/spider.py", line 483, in runSpiderScan
>    runSpiderScan(a, depth-1)
>  File "/home/bo0om/soft/Grabber/spider.py", line 480, in runSpiderScan
>    scan(entryUrl)
>  File "/home/bo0om/soft/Grabber/spider.py", line 147, in scan
>    parseHtmlLinks (currentURL,htmlContent)
>  File "/home/bo0om/soft/Grabber/spider.py", line 265, in parseHtmlLinks
>    parseJavaScriptCalls()
>  File "/home/bo0om/soft/Grabber/spider.py", line 373, in parseJavaScriptCalls
>    parseJavaScriptContent(jsContent)
>  File "/home/bo0om/soft/Grabber/spider.py", line 340, in parseJavaScriptContent
>    database_url.append(giveGoodURL(l[b1:b2],root))
>  File "/home/bo0om/soft/Grabber/spider.py", line 189, in giveGoodURL
>    return htmldecode(urlLocal + '/' + href)
>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1144: ordinal not in range(128)

**Comment by hdbreaker** [comment]
Hey i had the same problem, the problem is in the function: 
def parseHtmlParams(currentURL, htmlContent):

An ugly fix is try/except all code in this function and return True on except.

With this fix the scan finish without problem!
